version: "3.11"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:acronet
    container_name: clark_acronet
    command: python manage.py runserver 0.0.0.0:8000
