# Generated by Django 4.2.5 on 2023-10-24 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acronym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acronym_name", models.CharField(max_length=10)),
                ("full_form", models.CharField(max_length=70)),
                ("description", models.CharField(max_length=300)),
                ("location", models.CharField(max_length=20)),
                ("phone_number", models.IntegerField(max_length=10)),
                ("email", models.EmailField(max_length=50)),
                ("website", models.URLField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("admin", "Admin"), ("user", "User")], max_length=10
                    ),
                ),
                ("email", models.EmailField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Suggestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acronym_name", models.CharField(max_length=10)),
                ("full_form", models.CharField(max_length=70)),
                ("description", models.CharField(max_length=300)),
                ("location", models.CharField(max_length=20)),
                ("phone_number", models.IntegerField(max_length=10)),
                ("email", models.EmailField(max_length=50)),
                ("website", models.URLField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("pending", "Pending"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "suggested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="acronym.users"
                    ),
                ),
            ],
        ),
    ]
