# Generated by Django 4.2.5 on 2023-10-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acronym", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestions",
            name="suggested_by",
        ),
        migrations.AddField(
            model_name="suggestions",
            name="suggested_by_email",
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="suggestions",
            name="suggested_by_name",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
